baseURL = 'http://example.org/'
title = 'My New Hugo Site Hello World'
theme = "hugo-coder-main"

languageCode = "ja"
DefaultContentLanguage = "ja"

enableInlineShortcodes = true
footnoteReturnLinkContents = "^"