baseURL = 'http://example.org/'
title = 'My New Hugo Site Hello World Hello World'
theme = "starter-hugo-academic-master"

languageCode = "ja"
DefaultContentLanguage = "ja"

enableInlineShortcodes = true
footnoteReturnLinkContents = "^"